name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increased timeout for setup wizard
    strategy:
      matrix:
        php: ["8.1", "8.2"]  # Reduced PHP versions for faster CI
        browser: ["chrome"]   # Start with Chrome only for reliability

    services:
      mailpit:
        image: axllent/mailpit:latest
        ports:
          - 1025:1025
          - 8025:8025
        options: >-
          --health-cmd="wget --spider -q http://localhost:8025 || exit 1"
          --health-interval=2s
          --health-timeout=2s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache

      - name: Install NPM dependencies
        run: npm ci

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-cache

      - name: Install Composer dependencies
        run: composer install

      - name: Set PHP version for wp-env
        run: |
          echo "{\"config\": {\"phpVersion\": \"${{ matrix.php }}\"}}" > .wp-env.override.json

      - name: Start WordPress Test Environment
        run: npm run env:start:test

      - name: Wait for WordPress to be ready
        run: |
          for i in {1..60}; do
            if curl -s http://localhost:8889 | grep -q "WordPress"; then
              echo "WordPress is ready";
              break;
            fi
            echo "Waiting for WordPress... ($i/60)";
            sleep 5;
          done
          echo "Final check:"
          curl -s http://localhost:8889 || echo "WordPress not responding"

      - name: Debug WordPress Setup
        run: |
          echo "WordPress URL check:"
          curl -I http://localhost:8889 || echo "WordPress not responding"
          echo "WordPress admin check:"
          curl -I http://localhost:8889/wp-admin/ || echo "WP Admin not responding"
          echo "Network admin check:"
          curl -I http://localhost:8889/wp-admin/network/ || echo "Network admin not responding"

      - name: Run Setup Wizard Test (Must Run First)
        run: |
          npx cypress run --config-file cypress.config.test.js \
            --spec "tests/e2e/cypress/integration/setup-wizard-complete.spec.js" \
            --browser ${{ matrix.browser }} \
            --reporter spec \
            --reporter-options "verbose=true"

      - name: Run Checkout Tests (After Setup)
        if: success()
        run: |
          npx cypress run --config-file cypress.config.test.js \
            --spec "tests/e2e/cypress/integration/checkout-*.spec.js" \
            --browser ${{ matrix.browser }} \
            --reporter spec \
            --reporter-options "verbose=true"

      - name: Fix permissions for Cypress output
        if: always()
        run: sudo chown -R $USER:$USER tests/e2e/cypress

      - name: Upload Cypress screenshots
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.php }}-${{ matrix.browser }}
          path: tests/e2e/cypress/screenshots

      - name: Upload Cypress videos
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.php }}-${{ matrix.browser }}
          path: tests/e2e/cypress/videos

      - name: Fail job if tests failed
        if: failure()
        run: |
          echo "❌ One or more e2e tests failed."
          exit 1

      - name: Stop WordPress Environment
        if: always()
        run: npm run env:stop
