name: E2E Cross-Browser Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2"]
        browser: ["chrome", "firefox", "edge"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, pdo, pdo_mysql
          coverage: none
      
      - name: Install Composer dependencies
        run: composer install

      - name: Install NPM dependencies
        run: npm ci

      - name: Set PHP version for wp-env
        run: |
          echo "{\"config\": {\"phpVersion\": \"${{ matrix.php }}\"}}" > .wp-env.override.json

      - name: Start WordPress Environment
        run: npm run env:start

      - name: Wait for WordPress to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8888 | grep -q "WordPress"; then
              echo "WordPress is ready";
              break;
            fi
            echo "Waiting for WordPress... ($i/30)";
            sleep 5;
          done

      - name: Run Cypress Tests in ${{ matrix.browser }}
        run: |
          docker run --network host \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            cypress/included:latest \
            --browser ${{ matrix.browser }} \
            --config baseUrl=http://localhost:8888

      - name: Stop WordPress Environment
        if: always()
        run: npm run env:stop
