name: Unit & Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php-tests:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2, 8.3, 8.4]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports: [3306]
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    container:
      image: cimg/php:${{ matrix.php-version }}
      options: --user root # Ensure root access in container
    steps:
      - uses: actions/checkout@v4

      - name: Setup Composer Bin Path
        run: echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $GITHUB_ENV

      - name: Install System Dependencies
        run: |
          apt-get update && apt-get install -y subversion mariadb-client

      - name: Install PHP Extensions
        run: |
          install-php-extensions mysqli gd bcmath || echo "Extensions may already be installed."

      - name: Self-update Composer
        run: |
          composer self-update || echo "Composer update skipped due to permission issue."

      - name: Install PHP Dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Prepare WordPress Tests
        run: |
          rm -rf /tmp/wordpress-tests-lib /tmp/wordpress/
          bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
