name: Unit & Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php-tests:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2, 8.3, 8.4]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports: [3306]
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    container:
      image: cimg/php:${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment Variables
        run: echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $GITHUB_ENV
      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y subversion mariadb-client
          install-php-extensions mysqli gd bcmath
          composer self-update
      - name: Run Tests
        run: |
          composer install
          rm -rf /tmp/wordpress-tests-lib /tmp/wordpress/
          bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
          vendor/bin/phpunit
